apiVersion: v1
kind: Namespace
metadata:
  name: gitops-dr-simulator
  labels:
    app.kubernetes.io/name: gitops-dr-simulator
    app.kubernetes.io/part-of: gitops-dr-simulator
    app.kubernetes.io/component: application
